
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ConvexClientProvider from "./ConvexClientProvider";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full md:p-4 py-2  bg-green-300`}>
        <ConvexClientProvider>
         <div className="w-full h-full px-4">
         <Navbar />
          {children}
          
         </div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}